INSERT INTO BRANCH(STREET, BUILDING, PHONE)
VALUES ('Восстания', 15, '+79899999999');
INSERT INTO BRANCH(STREET, BUILDING, PHONE, UNFORMED)
VALUES ('Невский пр.', 32, '+79899999999', TO_DATE('15.01.2021','dd.mm.yyyy'));
INSERT INTO BRANCH(STREET, BUILDING, PHONE)
VALUES ('Адмиралтейская', 36, '+79899999999');
INSERT INTO BRANCH(STREET, BUILDING, PHONE, CREATED, UNFORMED)
VALUES ('Ленина', 188, '+79899991999', TO_DATE('01.02.2020','dd.mm.yyyy'), TO_DATE('12.12.2019','dd.mm.yyyy'));

INSERT INTO PERSON(NAME, SURNAME)
VALUES ('Иван', 'Иванов');
INSERT INTO PERSON(NAME, SURNAME)
VALUES ('Петр', 'Петров');
INSERT INTO PERSON(NAME, SURNAME)
VALUES ('Мария', 'Марчук');
INSERT INTO PERSON(NAME, SURNAME)
VALUES ('Евгений', 'Черненко');
INSERT INTO PERSON(NAME, SURNAME)
VALUES ('Денис', 'Денисенко');
INSERT INTO PERSON(NAME, SURNAME)
VALUES ('Александр', 'Александренко');
INSERT INTO PERSON(NAME, SURNAME)
VALUES ('Александр', 'Иванов');
INSERT INTO PERSON(NAME, SURNAME)
VALUES ('Владимир', 'Исаев');
INSERT INTO PERSON(NAME, SURNAME)
VALUES ('Олег', 'Афанасьев');


INSERT INTO COURSE(LANGUAGE, BRANCH_ID)
VALUES ('English', 1);
INSERT INTO COURSE(LANGUAGE, BRANCH_ID)
VALUES ('French', 1);
INSERT INTO COURSE(LANGUAGE, BRANCH_ID)
VALUES ('English', 3);

INSERT INTO STUDENT(PERSON_ID, COURSE_ID)
VALUES (1, 2);
INSERT INTO STUDENT(PERSON_ID, COURSE_ID)
VALUES (2, 1);
INSERT INTO STUDENT(PERSON_ID, COURSE_ID)
VALUES (3, 1);
INSERT INTO STUDENT(PERSON_ID, COURSE_ID)
VALUES (4, 3);
INSERT INTO STUDENT(PERSON_ID, COURSE_ID)
VALUES (5, 3);

INSERT INTO POSITION(DESCRIPTION)
VALUES ('Директор');
INSERT INTO POSITION(DESCRIPTION)
VALUES ('Преподаватель');
INSERT INTO POSITION(DESCRIPTION)
VALUES ('Администратор');

INSERT INTO EMPLOYEE(PERSON_ID, POSITION_ID, CONTRACT_ID, BRANCH_ID, SALARY)
VALUES (6, 1, 13141, 1, 60000);
INSERT INTO EMPLOYEE(PERSON_ID, POSITION_ID, CONTRACT_ID, BRANCH_ID, SALARY)
VALUES (6, 2, 13142, 1, 30000);
INSERT INTO EMPLOYEE(PERSON_ID, POSITION_ID, CONTRACT_ID, BRANCH_ID, SALARY)
VALUES (7, 2, 13143, 1, 35000);
INSERT INTO EMPLOYEE(PERSON_ID, POSITION_ID, CONTRACT_ID, BRANCH_ID, SALARY)
VALUES (8, 1, 45156, 2, 60000);
INSERT INTO EMPLOYEE(PERSON_ID, POSITION_ID, CONTRACT_ID, BRANCH_ID, SALARY)
VALUES (8, 3, 45157, 2, 20000);
INSERT INTO EMPLOYEE(PERSON_ID, POSITION_ID, CONTRACT_ID, BRANCH_ID, SALARY)
VALUES (9, 2, 45158, 2, 35000);