-- 1
SELECT
    BRANCH_ID, BRANCH.STREET, BRANCH.BUILDING, PERSON.NAME, PERSON.SURNAME, POSITION.DESCRIPTION
FROM
    BRANCH
    INNER JOIN EMPLOYEE USING (BRANCH_ID)
    INNER JOIN POSITION USING (POSITION_ID)
    INNER JOIN PERSON   USING (PERSON_ID)
WHERE
    POSITION.DESCRIPTION = 'Директор';

-- 2
SELECT
    EMPLOYEE.BRANCH_ID, PERSON.NAME, PERSON.SURNAME, POSITION.DESCRIPTION, EMPLOYEE.SALARY
FROM
    EMPLOYEE 
    INNER JOIN PERSON   USING (PERSON_ID)
    INNER JOIN POSITION USING (POSITION_ID)
WHERE
    EMPLOYEE.BRANCH_ID = 1;

-- 3
SELECT
    *
FROM
    BRANCH
WHERE
    CREATED > TO_DATE('01.01.2010','dd.mm.yyyy')
    AND UNFORMED < TO_DATE('01.01.2030','dd.mm.yyyy')
    AND CREATED > UNFORMED;

-- 4
SELECT
    BRANCH_ID, SUM(EMPLOYEE.SALARY)
FROM
    EMPLOYEE
GROUP BY
    BRANCH_ID
HAVING
    SUM(EMPLOYEE.SALARY) > (SELECT 
                AVG(SUM(EMPLOYEE.SALARY))
            FROM 
                EMPLOYEE
            GROUP BY BRANCH_ID);
    
-- 5
SELECT
    PERSON_ID, PERSON.NAME, PERSON.SURNAME
FROM
    PERSON
    INNER JOIN EMPLOYEE USING (PERSON_ID)
GROUP BY
    PERSON_ID, PERSON.NAME, PERSON.SURNAME
HAVING
    COUNT(EMPLOYEE.POSITION_ID) > 1;
    
