CREATE TABLE STORAGE(
    STORAGE_ID      INTEGER     PRIMARY KEY AUTOINCREMENT,
    STREET          VARCHAR(40) NOT NULL,
    BUILDING        INTEGER     NOT NULL
);

CREATE TABLE PRODUCT(
    PRODUCT_ID      INTEGER     PRIMARY KEY AUTOINCREMENT,
    VENDOR_CODE     VARCHAR(40) NOT NULL,
    CATEGORY        VARCHAR(40) NOT NULL,
    DESCRIPTION     VARCHAR(40) NOT NULL,
    MANUFACTURER    VARCHAR(40) NOT NULL,
    LOCATION        INTEGER     REFERENCES STORAGE(STORAGE_ID),
    PRICE           INTEGER     NOT NULL,
    RECEIVED_TIME   TIMESTAMP   NOT NULL,
    SOLD_TIME       TIMESTAMP
);
