CREATE TABLE PRODUCT(
    PRODUCT_ID      INTEGER     PRIMARY KEY AUTOINCREMENT,
    VENDOR_CODE     VARCHAR(30) NOT NULL,
    CATEGORY        VARCHAR(30) NOT NULL,
    DESCRIPTION     VARCHAR(30) NOT NULL,
    RECEIVED_DATE   DATE        DEFAULT CURRENT_DATE,
    SOLD_DATE       DATE
  );