INSERT INTO HOUSE(DISTRICT, STREET, NUM, TYPE, NUM_OF_FLOORS, SERIES)
    VALUES('Diamond District', '47th str.', 17, 'panel', 9, '9a815-91da');

INSERT INTO HOUSE(DISTRICT, STREET, NUM, TYPE, NUM_OF_FLOORS, SERIES)
    VALUES('Brooklyn', 'Coney Island avn.', 42, 'panel', 5, '1fa15-67da');

INSERT INTO HOUSE(DISTRICT, STREET, NUM, TYPE, NUM_OF_FLOORS, SERIES)
    VALUES('Manhattan', 'Wall str.', 24, 'bricks', 5, '34z3-014fx');

INSERT INTO HOUSE(DISTRICT, STREET, NUM, TYPE, NUM_OF_FLOORS, SERIES)
    VALUES('Manhattan', 'Broadway', 179, 'blocks', 12, 'a9710-3999');