CREATE TABLE PERSON(
    PERSON_ID       INTEGER     PRIMARY KEY AUTOINCREMENT,
    FIRST_NAME      VARCHAR(20) NOT NULL,
    SECOND_NAME     VARCHAR(20) NOT NULL,
    THIRD_NAME      VARCHAR(20) NOT NULL
);

CREATE TABLE CUSTOMER(
    CUSTOMER_ID    INTEGER     PRIMARY KEY AUTOINCREMENT,
    PERSON_ID      INTEGER     REFERENCES PERSON(PERSON_ID) NOT NULL,
    ADDRESS        VARCHAR(30) NOT NULL,
    PHONE          VARCHAR(13) NOT NULL UNIQUE
);

CREATE TABLE AUTHOR(
    AUTHOR_ID       INTEGER     PRIMARY KEY AUTOINCREMENT,
    PERSON_ID       INTEGER     REFERENCES PERSON(PERSON_ID) NOT NULL,
    NATIONALITY     VARCHAR(30) NOT NULL
);

CREATE TABLE GENRE(
    GENRE_ID        INTEGER     PRIMARY KEY AUTOINCREMENT,
    VALUE           VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE BOOK(
    BOOK_ID         INTEGER     PRIMARY KEY AUTOINCREMENT,
    AUTHOR_ID       INTEGER     REFERENCES AUTHOR(AUTHOR_ID),
    NAME            VARCHAR(30) NOT NULL,
    PUBLISHER       VARCHAR(30) NOT NULL,
    PUBLISHED       INTEGER     NOT NULL,
    GENRE           INTEGER     REFERENCES GENRE(GENRE_ID),
    PAGES           INTEGER     CHECK ( PAGES > 0 ) NOT NULL
);

CREATE TABLE RENT(
    RENT_ID         INTEGER     PRIMARY KEY AUTOINCREMENT,
    CUSTOMER_ID     INTEGER     REFERENCES CUSTOMER(CUSTOMER_ID),
    BOOK_ID         INTEGER     REFERENCES BOOK(BOOK_ID),
    DAY             DATE        NOT NULL,
    DURATION        INTEGER     CHECK ( DURATION > 0 ) NOT NULL
);